03/20/2021 11:32:29 AM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 139, in <module>
    user.delete_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 111, in delete_data
    self.save_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 51, in save_data
    file.write(information)
TypeError: write() argument must be str, not None
03/21/2021 05:17:56 PM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 158, in <module>
    user.welcome_screen()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 35, in welcome_screen
    self.update_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 110, in update_data
    self.save_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 73, in save_data
    file.write(information)
TypeError: write() argument must be str, not None
03/21/2021 05:20:19 PM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 146, in <module>
    user.welcome_screen()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 36, in welcome_screen
    self.update_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 83, in update_data
    option = int(input('Choose which data you want to update : \n1. First Name \n2. Last Name \n3. Address '
ValueError: invalid literal for int() with base 10: ''
03/21/2021 05:27:43 PM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 145, in <module>
    user.welcome_screen()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 36, in welcome_screen
    self.save_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 74, in save_data
    file.write(information)
TypeError: write() argument must be str, not None
03/21/2021 05:29:43 PM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 165, in <module>
    user.welcome_screen()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 36, in welcome_screen
    self.update_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 89, in update_data
    print('First Name : ', self._last_name)
AttributeError: 'User' object has no attribute '_last_name'
03/21/2021 06:31:50 PM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 157, in <module>
    welcome_screen(AddressBook())
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 22, in welcome_screen
    user.update_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 86, in update_data
    self.save_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 151, in save_data
    file.write(information)
TypeError: write() argument must be str, not None
03/21/2021 06:35:02 PM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 157, in <module>
    welcome_screen(AddressBook())
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 24, in welcome_screen
    user.delete_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 117, in delete_data
    self.save_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 151, in save_data
    file.write(information)
TypeError: write() argument must be str, not None
03/21/2021 06:42:09 PM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 164, in <module>
    welcome_screen(user)
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 22, in welcome_screen
    user.update_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 85, in update_data
    print('Pin Code : ', self._pin_code)
AttributeError: 'User' object has no attribute '_pin_code'
03/21/2021 07:03:47 PM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 158, in <module>
    welcome_screen(user)
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 22, in welcome_screen
    user_.update_data(user_)
TypeError: update_data() takes 1 positional argument but 2 were given
03/21/2021 10:29:35 PM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 166, in <module>
    welcome_screen(user)
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 25, in welcome_screen
    user_.update_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 74, in update_data
    self.save_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 159, in save_data
    file.write(information)
TypeError: write() argument must be str, not None
03/21/2021 10:29:57 PM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 166, in <module>
    welcome_screen(user)
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 25, in welcome_screen
    user_.update_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 74, in update_data
    self.save_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 159, in save_data
    file.write(information)
TypeError: write() argument must be str, not None
03/21/2021 11:11:05 PM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 167, in <module>
    welcome_screen(user)
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 27, in welcome_screen
    user_.delete_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 114, in delete_data
    self.save_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 160, in save_data
    file.write(information)
TypeError: write() argument must be str, not None
03/21/2021 11:15:42 PM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 167, in <module>
    welcome_screen(user)
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 27, in welcome_screen
    user_.delete_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 122, in delete_data
    self.save_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 160, in save_data
    file.write(information)
TypeError: write() argument must be str, not None
03/21/2021 11:17:56 PM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:/Pycharm Workshop/ProblemsSolvedUsingPython/object_oriented_programs/address_book.py", line 167, in <module>
    welcome_screen(user)
  File "D:/Pycharm Workshop/ProblemsSolvedUsingPython/object_oriented_programs/address_book.py", line 25, in welcome_screen
    user_.update_data()
  File "D:/Pycharm Workshop/ProblemsSolvedUsingPython/object_oriented_programs/address_book.py", line 79, in update_data
    self.save_data()
  File "D:/Pycharm Workshop/ProblemsSolvedUsingPython/object_oriented_programs/address_book.py", line 160, in save_data
    file.write(information)
TypeError: write() argument must be str, not None
03/22/2021 11:55:49 AM : logging_configuration.logging_config : 
Traceback (most recent call last):
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 174, in <module>
    user.retrieve_data()
  File "D:\Pycharm Workshop\ProblemsSolvedUsingPython\object_oriented_programs\address_book.py", line 165, in retrieve_data
    for data, information in file.read().split(':'):
ValueError: too many values to unpack (expected 2)
